### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Nandete84** [Tommimon/add-to-desktop#1]
I installed it and followed all instructions, but not working at all. It appears in tweaks/extensions, but no new line in the contextual menu...

I have left the extension installed, just in case an update becomes available, as I think it's a great idea.

**Comment by Tommimon** [comment]
Thanks for interesting in this project and for opening the issue I'm really interested in solving these problems.

Currently I don't have any Ubuntu machine but I tested it on the VM with clean Ubuntu 20.04 and everything worked for me.
Since I'm not able to reproduce this I need to see your shell output log to understand what's going on.

If you want to help this extension please post your logs following these steps:
1. To see shell output in console run `journalctl -f -o cat /usr/bin/gnome-shell`
2. Restart your shell, disable and enable this extension
3. Try to use it by right clicking some app
4. Copy your logs and post it here

**Comment by Nandete84** [comment]
Before restarting the shell:

`$ journalctl -f -o cat /usr/bin/gnome-shell
Gio.DBusError: Error calling StartServiceByName for org.freedesktop.FileManager1: Process org.freedesktop.FileManager1 exited with status 1
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
`
I restarted using ALT+F2 and this is the log:
$ journalctl -f -o cat /usr/bin/gnome-shell
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
GNOME Shell started at Tue Jun 30 2020 23:17:57 GMT+0100 (BST)
Registering session with GDM

**Comment by Tommimon** [comment]
It's very strange, here is some suggestion.

1. Maybe your extension isn't activated:
If you are using the extensions section in the tweaks app don't do that, for me using the extension app or using [GNOME](https://extensions.gnome.org/local/) web page solved many problems. Be sure that Add to Desktop is detected as ON.

2. Install from Add to Desktop [page](https://extensions.gnome.org/extension/3240/add-to-desktop/):
Cloning this repo also works for me but try the normal way.

If the extension code is not even executed I have nothing to work on

**Comment by Nandete84** [comment]
I first installed via Gnome, but it didn't work (you will see more comments in there from different people using Ubuntu 20.04).

Then, I installed it through a command in a terminal, but same result.

Finally, I decided to install it cloning the Git repository, but nothing.

The GUI is ok, all the links with tweaks and Gnome extensions works, but the extension won't start...

Maybe that's the problem?

I can keep trying different things if that helps.

**Comment by Tommimon** [comment]
Huge thanks for collaboration

I'm even more confused because currently the extension is designed to be almost independent from 'Desktop icons' and this is the reason why you have to allow launching in a second moment.

You can help other people facing this problem by finding out the proper way to solve it and explain it in a comment on the Add to Desktop extension [page](https://extensions.gnome.org/extension/3240/add-to-desktop/).

> I still need to type my password to add every icon

This should happen if the launcher file for this app is owned by another user, follow the shortcut to check if this is the case

> and select 'Allow launching' once they are in the desktop.

This is normal behaviour for now.

**Comment by Nandete84** [comment]
The solution I found is:
1.- Uninstall 'Desktop icons' extension
2.- Reinstall 'Desktop icons' extension _using the termial_
3.- Install 'Add to desktop' the way you choose
4.- Enjoy

Thanks @Tommimon for such a great extension and support.
