### ISSUE TITLE
It asks root password to create shortcut

### ISSUE THREAD

**Issue by mahmutelmas06** [Tommimon/add-to-desktop#2]
It asks root password to create shortcut

Debian 10
Gnome 3.30.2

**Comment by Tommimon** [comment]
Thanks for interesting in this extension.

This is the expected behaviour if the `.desktop` file (the launcher file) of that application is not owned by your current user, usually preinstalled apps files are owned by root.

This is a consequence of using symbolic links you can read more in the [README.md](https://github.com/Tommimon/add-to-desktop/blob/master/README.md).

I'm working to add this extension to the official [Desktop Icons](https://gitlab.gnome.org/World/ShellExtensions/desktop-icons) project in such a way that doesn't require passwords (using copies).

I can't go faster because I have to wait the maintainer approve this. if you are interested here is the [issue](https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/issues/210).

**Comment by mahmutelmas06** [comment]
That would be very nice if it is merged to Desktop Icons.
Thank you for answers.
