### ISSUE TITLE
The extension prevents user from moving icons in dock on PopOS 22.04

### ISSUE THREAD

**Issue by njdf18** [Tommimon/add-to-desktop#22]
(Sorry for my poor English)
I found that It will make user to not be able to move icons in dock on PopOS 22.04 after enabling this extension.

**Comment by Tommimon** [comment]
When you originally posted I encountered this same problem on my test machine but, after some updates, it seams to be fixed, can you confirm?

My current configuration:
- GNOME 42.4
- Dash to Dock for COSMIC v20
- Add to Desktop v7

**Comment by MB3hel** [comment]
I am running into the same issue with Ubuntu 22.04.
- Gnome 42.5
- Dash to Dock v75 (not Ubuntu dock; actual dash to dock)
- Add to Desktop v8

The issue is "fixed" by disabling then re-enabling dash to dock.

The issue returns by logging off and back on.

**Comment by MB3hel** [comment]
Interestingly (and possibly related), I am able to replicate #21 after the "fix" (disable and re-enable dash to dock). However, it works as intended before the "fix" for this issue.

**Comment by Tommimon** [comment]
I'm sorry to hear the issue is still there.

Can you try to use [Dash to Dock for COSMIC](https://extensions.gnome.org/extension/5004/dash-to-dock-for-cosmic/)? Is a fork of the original Dash to Dock. I'm using it right know and I don't see problems.

Meanwhile I will try to recreate your configuration on a vm and do some testing.

**Comment by Tommimon** [comment]
I was able to reproduce it in a vm. From what I can see with my tests the new code solves both this and #21.

Let me know if you are still facing any problem.
