### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by mahmutelmas06** [Tommimon/add-to-desktop#3]
How can we could add languages other than English ?

**Comment by Tommimon** [comment]
I'm sorry to inform you that other languages aren't supported.

Sincerely I don't know if or when I will add language support because I never done that and I don't have always time to work on this extension.

If this extension will be added to (Desktop Icons)[https://gitlab.gnome.org/World/ShellExtensions/desktop-icons] project. it will be translated. I hope this happens soon.

If someone wants to add the language support to this extension contribution is appreciated.

**Comment by Tommimon** [comment]
I added language  support.

To add a new language create a pull request with a new `.po` file in the po folder, you can use the already existing files in po folder as template.

If you want to improve a translation you can edit the corresponding file and create a pull request.
