### ISSUE TITLE
Update to GNOME 46 and 47

### ISSUE THREAD

**Issue by Nekothegamer** [Tommimon/add-to-desktop#33]
Please update to GNOME 46 and 47, i really need this to use the desktop icons please

**Comment by Tommimon** [comment]
Version 13 is compatible with GNOME 46 and 47, closing the issue.

I noticed that the `46.beta` entry in the `manifest.json` caused a lot of confusion, because the extension was marked as incompatible with GNOME 46 on some applications even if it was actually working. I will avoid this kind of versioning in the future and use only major version numbers. I learned I can use them on GSE website even if the final release is not out yet.

**Comment by Tommimon** [comment]
Version 13 is compatible with GNOME 46 and 47, closing the issue
